config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index', as: :homepage
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create' 
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  get '/search' => 'search#index'
  
  resources :art
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  match '*unmatched', to: 'application#route_not_found', via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/art.rb
class Art < ApplicationRecord
  
  belongs_to :user
  
  validates :name, presence: true, length: {maximum: 20}
  validates :image, presence: true
  validates :description, presence: true, length: {maximum: 25}
  validates :user_id, presence: true

  def self.search(search)
    if search
      
      where('LOWER(name) LIKE :search OR LOWER(description) LIKE :search', search: "%#{search.downcase}%") #add abiltiy to search by description too
      
      else
        Art.all
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :arts
  has_secure_password

  validates :username, presence: true, length: {minimum: 5}, uniqueness: {:case_sensitive => false}
  validates :username, length: {minimum: 5}
  validates :password, presence: true
  validates :password, length: { minimum: 5 }

def self.authenticate_with_credentials(username, password)
  user = User.find_by_username(username)
  if user && user.authenticate(password)
    user
  else
    nil
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user
before_action :authorized
  def current_user
    User.find_by(id: session[:user_id])  
end
def authorized
  redirect_to '/login' unless current_user
end

def route_not_found
  render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
end

end

app/controllers/art_controller.rb
class ArtController < ApplicationController
  
  def index
    @arts = current_user.arts
    @art = current_user.id
end

  def show
    @arts = Art.find params[:id]
    @art = current_user.id
  end

  def new
    @art = Art.new
end

  def create
    @art = Art.new(art_params)
    if @art.valid?
        @art.user = current_user
        @art.save
        redirect_to "/art"
else
  flash[:danger] = "All fields need to be filled.
                    Title length can be no more that 10 characters. 
                    Description length can be no more than 25 characters"
      redirect_to "/art/new"
end
  end

  def destroy

    @art = Art.find params[:id]
    if @art.destroy
    flash[:notice] = "Deleted" 
    redirect_to "/art"
    
    end
  end

  private

  def art_params
    params.require(:art).permit(
      :id,
      :name,
      :description,
      :image,
      :user_id,
      :search
    ).merge(user: current_user)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    
    @arts = Art.search(params[:search])
    @art = current_user.id

  
  end

#   def personal_index
#     render "index.html.erb"
#   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def create
    user = User.authenticate_with_credentials(params[:username], params[:password])
    if user
       session[:user_id] = user.id
       redirect_to '/art'
    else
      flash[:danger] = "There is a problem with your username or password"
       redirect_to '/login'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def create
    user = User.new(user_params)
    if user.save
    session[:user_id] = user.id
    redirect_to '/art'
    else
      flash[:danger] = "All fields need to be filled correctly"
      redirect_to '/signup'
end
end

private
def user_params
  params.require(:user).permit(:username, :password)
  end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorized, only: [:index]
  def index
    @arts = Art.search(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/art/index.html.erb
<div>
<h1 class="page-header">Art</h1>
 </div>
 <% if flash[:notice] %>
 <div class="delete_msg"><%= flash[:notice] %></div>
 <% end %>
 <% if @arts.blank? %>
 <div class="message">
 <p>No art added yet</p>
 <% end %>
 </div>

<section class="container-index">

 <% @arts.each do |art| %>
  
    <div>
      <div class="title">
      <%= art.name %>
      </div>

      <div class="img-index">
      <%= image_tag art.image, style:"width:100%; height: auto"%>
      </div>
      <br><br>
      <div class="desc">
      <%= art.description %>
      </div>

      <div class="view">
      <%= link_to 'View', art_path(art) %>
              </div>
              </div>
<% end %>


</section>

app/views/art/new.html.erb
<h1 class="art_title">Add new Art</h1>


<%= form_for @art, url: art_index_path do |f| %>
  <div class="signup_title">
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :url %><br>
    <%= f.url_field :image %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
</div>
<% end %>

<% if flash[:danger] %>
<div class="create_err"><%= flash[:danger] %></div>
<% end %>

app/views/art/show.html.erb
<section class="container-show">

  <header class="page-header">
   <%= @arts.name %>
  </header>

  <article class="art">

      <div class="img">
        <%= image_tag(@arts.image) %>
      </div>

     <div class="desc">
       <%= @arts.description %>
      </div>
<% if @arts.user_id === @art%>
      <div class="delete">
      <%=link_to 'Delete', art_path(@arts),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
              </div>
              <% end %>

            
  </article>
 
</section>

app/views/layouts/_top_nav.html.erb
<nav>
      <a class="navbar" href="/">Home</a>
      <a class="navbar" href="/art">My Art</a>
      <a class="navbar" href="/art/new">Create New</a>
      <%= form_tag(search_url, method: :get) do %>
          <%= search_field_tag(:search, params[:search], required: true) %>
          <%= submit_tag ("Search") %>
      <% end %>
<% if !current_user %>
<a class="navbar-login" href="/login">Login</a>
<a class="navbar-user" href="/signup">Signup</a>
<% else %>
<div class="navbar-logout">You are Logged In as <%= current_user.username %></div>
<a href="/logout" class="logout">Logout</a>
<% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <% unless controller_name == "welcome" %> 
  
  <%# seperate nav bar for welcome so all art can be searched for on welcome page %>
  <%= render 'layouts/top_nav'%>
  <% end %>
    <%= yield %>
    
  </body>
</html>

app/views/search/index.html.erb
<div>
<h1 class="page-header">Art</h1>
 </div>


<section class="container-index">

 <% @arts.each do |art| %>
  <% if art.user_id === @art %>
    <div>
      <div class="title">
      <%= art.name %>
      </div>

      <div class="img-index">
      <%= image_tag art.image, style:"width:100%; height: auto"%>
      </div>
      <br><br>
      <div class="desc">
      <%= art.description %>
      </div>

      <div class="view">
      <%= link_to 'View', art_path(art) %>
              </div>
              </div>

<% else %>
  <div class="messagetwo">
  <p>No art found</p>
  </div>
   
<% end %>

<% end %>
</section>

  
<%# first error message is for when searched art does not exist at all, seccond error is for when art does exist but is owned by another user %>

app/views/users/new.html.erb
<h1 class="signup_title">Sign Up</h1>
<div class="user_signup">
<%= form_for :user, url: '/users' do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>
</div>
<% if flash[:danger] %>
<div class="signup_msg"><%= flash[:danger] %></div>
<% end %>

app/views/welcome/index.html.erb
<nav>
      <a class="navbar" href="/">Home</a>
      <a class="navbar" href="/art">My Art</a>
      <a class="navbar" href="/art/new">Create New</a>
      <%= form_tag("/", method: :get) do %>
          <%= search_field_tag(:search, params[:search], required: true) %>
          <%= submit_tag ("Search") %>
      <% end %>
<% if !current_user %>
<a class="navbar-login" href="/login">Login</a>
<a class="navbar-user" href="/signup">Signup</a>
<% else %>
<div class="navbar-logout">You are Logged In as <%= current_user.username %></div>
<a class="logout"href="/logout">Logout</a>
<% end %>

</nav>

<h1 class="art_title"> Community Art Board</h1>


<section class="container-index">

 <% @arts.each do |art| %>
  
    <div>
      <div class="title">
      <%= art.name %>
      </div>
      
      <div class="img-index">
      <%= image_tag art.image, style:"width:100%; height: auto"%>
      </div>
      <br><br>
      <div class="desc">
      <%= art.description %>
      </div>

      <div class="view">
      <%= link_to 'View', art_path(art) %>
              </div>
              </div>
   
<% end %>


</section>